Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2023-12, with the labels that each got.

#318 Add Stalwart Mail Server to Communication - Email - Complete Solutions
  software/stalwart-mail-server.yml
Labels: addition

#369 Add Smederee
  software/smederee.yml
Labels: addition

#394 Add Digibuzzer
  software/digibuzzer.yml
Labels: addition

#401 Add Bracket
  software/bracket.yml
Labels: addition

#415 Fix Stalwart Mail Server homepage URL
  software/stalwart-mail-server.yml
Labels: bug

#416 Remove PicApport (demo and documentation down, cannot find source code)
  software/picaport.yml
Labels: curation

#425 remove bigbluebutton demo link
  software/bigbluebutton.yml
Labels: bug, curation

#426 add demo url for jitsi meet
  software/jitsi-meet.yml
Labels: enhancement

#432 Update Synapse source code URL
  software/synapse.yml
Labels: bug

#433 Update Inboxen source code URL
  software/inboxen.yml
Labels: bug

#411 Add Digipad to Groupware
  software/digipad.yml
Labels: addition

#430 Remove BluetoothCommunicatorExample (unmaintained since October 2022)
  software/bluetoothcommunicatorexample.yml
Labels: curation

#438 Add awesome-web-archiving to external links
  tags/archiving-and-digital-preservation-dp.yml
Labels: enhancement

#423 Add WebDB
  software/webdb.yml
Labels: addition

#420 Add Azimutt software
  software/azimutt.yml
Labels: addition

#429 tools: ignore last update date check on Writing
  .hecat/awesome-lint-strict.yml
  .hecat/awesome-lint.yml
Labels: curation, reviewers wanted

#439 Remove notesntodos (unmaintained since 2021)
  software/notes'n'todos.yml
Labels: curation

#440 Remove newsdash (unmaintained since December 2022)
  software/newsdash.yml
Labels: curation

#441 Remove Mailtrain (unmaintained since december 2022)
  software/mailtrain.yml
Labels: curation

#442 Remove Kutt (unmaintained since November 2022)
  software/kutt.yml
Labels: curation

#443 Remove Jam (unmaintained since December 2022)
  software/jam.yml
Labels: curation

#444 Remove OS.js (unmaintained since September 2022)
  software/os.js.yml
Labels: curation

#427 Add Digiwords to Miscellaneous
  software/digiwords.yml
Labels: addition

#446 Remove Screensy (project gone/404)
  software/screensy.yml
Labels: bug

#434 added tasmota
  software/tasmota.yml
Labels: addition

#407 Add Dify
  software/dify.yml
Labels: addition

#451 Update transfer.sh homepage URL
  software/transfer.sh.yml
Labels: bug

#448 Remove Teddit (no longer maintained, website down)
  software/teddit.yml
Labels: curation

#449 Remove Lenpaste (website/source code unreachable)
  software/lenpaste.yml
Labels: curation

#450 Remove Atman IOT (certificate expired)
  software/atman-iot.yml
Labels: curation, non-free

#452 Remove MapBBCodeShare (unmaintained since 2020)
  software/mapbbcodeshare.yml
Labels: curation

#455 Remove tine Community Edition (the project is archived)
  software/tine---community-edition.yml
Labels: bug
