Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2023-09, with the labels that each got.

#110 Update Lynx demo URL
  software/lynx.yml
Labels: enhancement

#89 Add cerbos.yml
  software/cerbos.yml
Labels: addition

#102 Remove ReducePy (unmaintained since April 2022)
  software/reducepy.yml
Labels: curation

#103 Remove HRCloud2 (Unmaintained since April, 2022)
  software/hrcloud2.yml
Labels: curation

#105 Remove Groceri.es (Abandoned/Unmaintained Since Jul 2022)
  software/groceri.es.yml
Labels: curation

#104 Remove horde (unmaintained since Feb, 2022)
  software/horde.yml
Labels: curation

#91 Add Forgejo
  software/forgejo.yml
Labels: addition

#96 Remove Kolab (website and source code link down)
  software/kolab.yml
Labels: curation

#99 Remove pacebin (expired certificates, unmaintained since Feb. 2022)
  software/pacebin.yml
Labels: curation

#128 Remove Searx (the project is archived)
  software/searx.yml
Labels: curation

#125 Remove Hadmean demo link
  software/hadmean.yml
Labels: bug, curation

#126 tests/url-check: whitelist Memories demo URL
  .hecat/url-check.yml
Labels: bug, curation

#143 Remove exatorrent (the project is archived)
  software/exatorrent.yml
Labels: curation

#117 platforms: add `deb` platform for software that can be installed trough .deb packages
  platforms/deb.yml
  software/asterisk.yml
  software/courier-mta.yml
  software/dovecot.yml
  software/exim.yml
  software/iodine.yml
  software/jellyfin.yml
  software/jitsi-meet.yml
  software/jitsi-video-bridge.yml
  software/kamailio.yml
  software/mumble.yml
  software/nextcloud.yml
  software/ngircd.yml
  software/opensmtpd.yml
  software/openssh-sftp-server.yml
  software/postfix.yml
  software/privoxy.yml
  software/roundcube.yml
  software/sendmail.yml
  software/shaarli.yml
  software/squid.yml
  software/tinyproxy.yml
  software/transmission.yml
  software/weechat.yml
  software/zim.yml
  software/znc.yml
Labels: enhancement

#111 add Sosse software
  software/sosse.yml
Labels: addition

#114 Add Flipt to Miscellaneous
  software/flipt.yml
Labels: addition

#135 Remove Gitlist (Unmaintained since July 2022)
  software/gitlist.yml
Labels: curation

#123 Add mataroa blogging platform
  software/mataroa.yml
Labels: addition

#131 ➕ Add the new `websurfx` project under search engine category
  software/websurfx.yml
Labels: addition

#115 Add INGInious to Learning and Courses
  software/inginious.yml
Labels: addition

#160 Remove PolitePol from Feed Readers
  software/politepol.yml
Labels: curation

#167 Corrections to Rallly data
  software/rallly.yml
Labels: bug, enhancement

#152 Update CUPS source code URL
  software/cups.yml
Labels: bug

#174 Fix demo/source code URL/description for Gramps Web
  software/gramps-web.yml
Labels: bug

#175 Fix MedusaJS demo URL
  software/medusajs.yml
Labels: bug

#177 tools: update hecat to v1.1.2
  .hecat/awesome-lint.yml
  CONTRIBUTING.md
  Makefile
  software/forgejo.yml
Labels: bug, tools

#178 tools: update hecat to v1.1.3
  Makefile
Labels: bug, tools

#181 Fix Plausible Analytics license
  software/plausible-analytics.yml
Labels: bug

#189 Remove OhMyForms (the project is archived)
  software/ohmyforms.yml
Labels: bug

#170 Remove Pomf (Unmaintained since April 2022)
  software/pomf.yml
Labels: curation

#182 Remove Feedka (Unmaintained since November 2022, Outdated dependencies)
  software/feedka.yml
Labels: curation

#185 Remove RSS Fulltext Proxy (unmaintained since 2019)
  software/rss-fulltext-proxy.yml
Labels: curation

#186 Remove Recepturer (unmaintained since August 2022)
  software/recepturer.yml
Labels: curation

#187 Remove Quru Image server (unmaintained since June 2022)
  software/quru-image-server.yml
Labels: curation

#190 rename Hoppscotch to Hoppscotch Community Edition
  platforms/nuxt.yml
  platforms/vue.yml
  software/hoppscotch.yml
Labels: bug

#191 group .NET/.NET Core platforms
  platforms/.net-core.yml
  software/kavita.yml
Labels: enhancement

#192 Fix SIP3 platform
  platforms/kotlin.yml
  software/sip3.yml
Labels: bug

#193 Fix Daneecloud platforms
  platforms/ejs.yml
  software/daneecloud.yml
Labels: bug

#194 Fix Evergreen platform/language
  platforms/pl.yml
  platforms/plpgsql.yml
  software/evergreen.yml
Labels: bug

#195 rename Nimble platform to Nim
  platforms/nim.yml
  platforms/nimble.yml
  software/nitter.yml
Labels: enhancement

#196 group Calendar & Contacts Servers/Web-based clients under a single Calendar & Contacts section
  .github/ISSUE_TEMPLATE/addition.md
  software/baïkal.yml
  software/calypso.yml
  software/davical.yml
  software/davis.yml
  software/etebase-etesync.yml
  software/etesync-web.yml
  software/manage-my-damn-life.yml
  software/radicale.yml
  software/sabredav.yml
  software/xandikos.yml
  tags/calendar--contacts---caldav-or-carddav-servers.yml
  tags/calendar--contacts---caldav-or-carddav-web-based-clients.yml
Labels: bug

#197 fix SIPCAPTURE HOMPER language/platform
  platforms/angular.yml
  software/sipcapture-homer.yml
Labels: bug

#198 use Ansible platform for all projects using ansible
  platforms/yaml.yml
  software/ansible-nas.yml
  software/debops.yml
  software/xsrv.yml
Labels: enhancement

#202 Fix Guacamole source code
  software/guacamole.yml
Labels: bug

#203 Remove rport (Source Code removed, project closed)
  software/rport.yml
Labels: bug, curation

#208 Remove duplicate Hoppscotch entry
  software/hoppscotch-community-edition.yml
Labels: bug

#200 add more `deb` platform tags
  software/0-a.d..yml
  software/calypso.yml
  software/davical.yml
  software/minetest.yml
  software/radicale.yml
  software/red-eclipse-2.yml
  software/teeworlds.yml
  software/the-battle-for-wesnoth.yml
  software/xandikos.yml
Labels: enhancement

#216 fix Upsnap platform
  platforms/svelte.yml
  software/upsnap.yml
Labels: bug

#199 remove Homehost (unmaintained since March 2023, untriaged issues)
  software/homehost.yml
Labels: curation

#201 Remove filite (unmaintained since Apr 2023)
  software/filite.yml
Labels: curation

#204 Remove librengine (project unmaintained since Jun 2023)
  software/librengine.yml
Labels: curation

#206 Remove pootle (using unsupported python version)
  software/pootle.yml
Labels: curation

#209 Remove Dudle (unmaintained since Aug 25, 2022)
  software/dudle.yml
Labels: curation

#210 Remove Chowdown (unmaintained since February 2022)
  software/chowdown.io.yml
Labels: curation

#212 Remove Logpaste (unmaintained since August 2022)
  software/logpaste.yml
Labels: curation

#218 remove Pastila (proof-of-concept/demo app for ClickHouse)
  platforms/sql.yml
  software/pastila.yml
Labels: curation, reviewers wanted

#219 remove Bitsii Bridge (unmaintained since July 2022)
  software/bitsii-bridge.yml
Labels: curation

#214 Remove Kazoo (unmaintained since August 2022)
  software/kazoo.yml
Labels: curation

#215 Remove Mojopaste (unmaintained since January 2022)
  software/mojopaste.yml
Labels: curation

#220 merge HTML5 platform with Javascript, add description
  platforms/html5.yml
  platforms/javascript.yml
  software/a-dark-room.yml
  software/bicimon.yml
  software/cubiks-2048.yml
  software/h3-viewer.yml
  software/hiccup.yml
  software/homebank-converter.yml
  software/littlelink.yml
  software/markdown-edit.yml
Labels: enhancement, curation

#221 add descriptions for all platforms, misc. fixes and adjustments to platforms
  platforms/assembly.yml
  platforms/bash.yml
  platforms/c#.yml
  platforms/clearos.yml
  platforms/commonlisp.yml
  platforms/crystal.yml
  platforms/django.yml
  platforms/docker.yml
  platforms/erlang.yml
  platforms/go.yml
  platforms/haskell.yml
  software/citadel.yml
  software/domoticz.yml
  software/easywi.yml
  software/emailwiz.yml
  software/maza-ad-blocking.yml
  software/mistborn.yml
  software/nextcloudpi.yml
  software/wikisuite.yml
Labels: enhancement, curation

#222 Update Cosmos licence
  software/cosmos.yml
Labels: bug
