Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2023-10, with the labels that each got.

#148 Add Note-Mark
  software/note-mark.yml
Labels: addition

#240 Update benphelps/homepage to gethomepage/homepage
  software/homepage-by-gethomepage.yml
Labels: bug

#260 Update URL for Tiki source code
  software/tiki.yml
Labels: bug

#230 Add Specifically Clementines
  software/specifically-clementines.yml
Labels: addition

#231 Add Deluge
  software/deluge.yml
Labels: addition

#259 Update Jami Source Code Link
  software/jami.yml
Labels: bug

#261 tools: update hecat to v1.2.0
  Makefile
Labels: enhancement

#262 tools: update hecat to v1.2.0 (#261)
  .hecat/conf.py
  Makefile
Labels: enhancement

#258 Update Dovel Source Code Link
  software/dovel.yml
Labels: bug

#265 Remove Bluemind (Dead Source Code)
  software/bluemind.yml
Labels: bug, curation

#228 Remove Livekit
  software/livekit.yml
Labels: curation

#247 Change DailyTxt tag to Note-taking & Editors
  software/dailytxt.yml
Labels: enhancement

#248 Change Readflow tag to Feed Readers
  software/readflow.yml
Labels: enhancement

#249 Change Wallabag tag to Archiving and Digital Preservation (DP)
  software/wallabag.yml
Labels: enhancement

#253 Remove Maildrop (Unmaintained since Jan 2022)
  software/maildrop.yml
Labels: curation

#254 Remove Oddworks (Unmaintained since 2019)
  software/oddworks.yml
Labels: curation

#255 Remove Olaris (Unmaintained Since July 2022)
  software/olaris.yml
Labels: curation

#256 Remove Shinobi (Unmaintained since Feb 2021)
  software/shinobice.yml
Labels: curation, non-free

#257 Remove Stone-Age Messenger (Unmaintained since May 2021)
  software/stoneage-messenger.yml
Labels: curation

#263 Remove Airsonic Advanced (Untriaged Issues and vulnerabilities)
  software/airsonic-advanced.yml
Labels: curation

#264 Remove Manager (Dead Link)
  software/manager.yml
Labels: curation, non-free

#266 Remove OpenGTS (Unmaintained since Feb 2020)
  software/opengts.yml
Labels: curation

#267 Update Pagure Platform
  software/pagure.yml
Labels: enhancement

#269 Update ACP-Admin Description
  software/acp-admin.yml
Labels: enhancement

#274 Update Owncast website URL
  software/owncast.yml
Labels: enhancement

#275 add Video Surveillance tag
  software/bluecherry.yml
  software/frigate.yml
  software/kerberos.io.yml
  software/zoneminder.yml
  tags/media-streaming---multimedia-streaming.yml
  tags/media-streaming---video-streaming.yml
  tags/video_surveillance.yml
Labels: enhancement, reviewers wanted

#279 Update DamselFly Source Code
  software/damselfly.yml
Labels: bug

#282 Update OctoBot link
  software/octobot.yml
Labels: bug

#289 Remove duplicated cncjs
  software/CNCjs.yml
Labels: bug

#273 Remove Savepad (Unmaintained since December 2022)
  software/savepad.yml
Labels: curation

#271 Remove B2 Evolution (Unmaintained since September 2022)
  software/b2evolution-cms.yml
Labels: curation

#246 Add Browserstack Automate Turboscale
  software/browserstack-automate-turboscale.yml
Labels: addition, non-free

#277 Remove Musical Artifacts (Unmaintained since June 2022)
  software/musical-artifacts.yml
Labels: curation

#245 Add rs-short
  software/rs-short.yml
Labels: addition

#278 Remove Calypso (Unmaintained since May 2021)
  software/calypso.yml
Labels: curation

#283 Update Galette website URL
  software/galette.yml
Labels: curation

#284 Remove ICECoder (unmaintained since 2022, not compatible with PHP8)
  software/icecoder.yml
Labels: curation

#285 Remove Pasty (unmaintained since February 2022)
  software/pasty.yml
Labels: curation

#303 Update Hadmean to Dashpress
  software/dashpress.yml
Labels: bug

#313 Remove Eonza Demo
  software/eonza.yml
Labels: bug, reviewers wanted

#291 Add Clustercontrol to Database Management
  software/clustercontrol.yml
Labels: addition, non-free

#316 Remove This week in past demo (Timesout)
  software/this-week-in-past.yml
Labels: bug

#314 Exclude links from checker / Remove Hackershare demo
  .hecat/url-check.yml
  software/hackershare.yml
Labels: curation

#305 improve related tags, merge Enterprise Resource Planning with Resource Planning
  software/dolibarr.yml
  software/erpnext.yml
  software/ledgersmb.yml
  software/odoo.yml
  software/ofbiz.yml
  software/tryton.yml
  software/yetiforce.yml
  tags/games---administrative-utilities--control-panels.yml
  tags/games.yml
  tags/inventory-management.yml
  tags/money-budgeting--management.yml
  tags/resource-planning---enterprise-resource-planning.yml
  tags/resource-planning.yml
Labels: enhancement

#302 Remove Silverstrike (Unmaintained, Dead Links)
  software/silverstrike.yml
Labels: curation

#306 Remove twiki (Unmaintained since 2018)
  software/twiki.yml
Labels: curation

#307 Remove Jirafeau (Unmaintained since July 2022)
  software/jirafeau.yml
Labels: curation

#309 Remove Instiki (Unmaintained since March 2023)
  software/instiki.yml
Labels: curation

#311 Remove Euterpe (Outdated ICU Version)
  software/euterpe.yml
Labels: curation

#317 Remove Thredded (Outdated Ruby Version)
  software/thredded.yml
Labels: curation

#321 tools: update hecat to v1.2.1
  Makefile
Labels: bug, enhancement, tools

#298 Add Servas to Bookmarks and Link Sharing
  software/servas.yml
Labels: addition

#328 Inlets is proprietary now :(
  software/inlets.yml
Labels: bug, non-free
