Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2023-08, with the labels that each got.

#56 remove Tanoshi (the project is archived)
  software/tanoshi.yml
Labels: bug, curation

#57 footer: external links: update communities/forums links
  markdown/footer.md
Labels: documentation, enhancement

#54 markdown/header: add links to HTML and markdown versions
  markdown/header.md
Labels: enhancement

#53 tools/export_html: footer: add a link to the HTML source git repository and YAML data
  Makefile
Labels: enhancement, tools

#61 tools/makefile: export_html: generate robots.txt
  Makefile
Labels: enhancement, tools

#62 tools/github actions: do not run scheduled jobs on forks of the original repository
  .github/workflows/check-dead-links.yml
  .github/workflows/check-unmaintained-projects.yml
  .github/workflows/daily-update-metadata.yml
Labels: enhancement, tools

#63 tools: switch deployment targets to awesome-selfhosted/awesome-selfhosted(-html)
  .github/workflows/build.yml
  CONTRIBUTING.md
  Makefile
Labels: tools

#64 doc: mention both HTML and markdown versions in the README
  README.md
Labels: documentation, enhancement

#39 Remove GNU FM (unmaintained since 2014)
  software/gnu-fm.yml
Labels: curation

#73 contributing: link to awesome-selfhosted liberapay account
  CONTRIBUTING.md
Labels: documentation, reviewers wanted

#42 Software Development - FaaS & Serverless: update description
  tags/software-development---faas--serverless.yml
Labels: enhancement

#67 revert: Remove Ubergallery.yml
  software/ubergallery.yml
Labels: curation

#69 revert: Remove Syspass.yml
  software/syspass.yml
Labels: curation

#70 revert: Remove Restyaboard.yml
  software/restyaboard.yml
Labels: curation

#81 revert: Remove Volumio.yml
  software/volumio.yml
Labels: curation

#83 revert: Remove Schort.yml
  software/schort.yml
Labels: curation

#85 revert: Remove Party Poker
  software/party-poker.yml
Labels: curation

#86 revert: Remove Keeja.yml
  software/kleeja.yml
Labels: curation

#38 Remove GNU Social (unmaintained since Nov 2022, website down)
  software/gnu-social.yml
Labels: curation

#88 correction: Correct Transmission language
  software/transmission.yml
Labels: enhancement

#79 Remove CRATER (Abandoned)
  software/crater.yml
Labels: curation

#80 Update source code URL for Sympa
  software/sympa.yml
Labels: enhancement

#94 standardize 'fork of' mentions syntax
  software/calypso.yml
  software/gitea.yml
  software/jellyseerr.yml
  software/kanbana.yml
  software/metronome-im.yml
  software/pairdrop.yml
  software/paperless-ngx.yml
  software/searxng.yml
  software/snappymail.yml
Labels: enhancement

#95 doc/PR/issue template: forks must provide a list of differences with upstream
  .github/ISSUE_TEMPLATE/addition.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#107 Update atsumeru.yml (Add tag)
  software/atsumeru.yml
Labels: curation

#66 feat: Add Janus
  software/janus.yml
Labels: addition

#74 feat: Add Review Board
  software/review-board.yml
Labels: addition
