Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2023-11, with the labels that each got.

#322 tools/hecat: do not warn about last update date for homepage, posio, bicimon, cubiks-2048
  .hecat/awesome-lint-strict.yml
  .hecat/awesome-lint.yml
Labels: tools, curation

#335 tools: update hecat to v1.2.2
  Makefile
Labels: bug, tools

#334 Added links to URL Check and Removed Psychic URL
  .hecat/url-check.yml
  software/psychic.yml
Labels: tools, curation

#337 Remove MediaHut (the project is archived)
  software/mediahut.yml
Labels: curation

#338 Update Alfresco Community source code link
  software/alfresco-community-edition.yml
Labels: enhancement

#304 Add Digistorm to Groupware
  software/digistorm.yml
Labels: addition

#324 Adds DocKing to Document Management
  software/docking.yml
Labels: addition

#329 Add Flyimg project
  software/flyimg.yml
Labels: addition

#331 StartOS is now MIT
  software/startos.yml
Labels: curation

#325 add Digiscreen
  software/digiscreen.yml
Labels: addition

#333 Add SentryShot
  software/sentryshot.yml
Labels: addition

#280 Add kestra in the automation section.md
  software/kestra.yml
Labels: addition

#347 Add Digitools to Learning and Courses / Groupware
  software/digitools.yml
Labels: addition

#336 Add An Otter Wiki
  software/otterwiki.yml
Labels: addition

#365 doc/fix: depends_3rdparty must be a valid boolean value (true/false/True/False)
  .github/ISSUE_TEMPLATE/addition.md
  software/flyimg.yml
  software/forgejo.yml
  software/inginious.yml
  software/websurfx.yml
Labels: bug

#372 remove vSMTP (project was deleted)
  software/vsmtp.yml
Labels: bug, curation

#373 remove feed2toot (unmaintained since December 2022)
  software/feed2toot.yml
Labels: curation

#374 mastodon: add related_software_url (Clients) link
  software/mastodon.yml
Labels: enhancement

#290 Add DocuSeal to Document Management
  software/docuseal.yml
Labels: addition

#339 Add ESMira
  software/esmira.yml
Labels: addition

#340 Add LanguageTool
  software/languagetool.yml
Labels: addition

#349 Add Librum
  software/librum.yml
Labels: addition

#350 Add Suroi.io to Games
  software/suroi.yml
Labels: addition

#351 Add Homebox to Inventory Management apps
  software/homebox-inventory.yml
Labels: addition

#353 Add Slash to Bookmarks and Link Sharing
  software/slash.yml
Labels: addition

#359 tools: exclude Simple-URL-Shortener from last update checks
  .hecat/awesome-lint-strict.yml
  .hecat/awesome-lint.yml
Labels: curation

#376 jellyfin: related_software_url: add link to awesome-jellyfin
  software/jellyfin.yml
Labels: enhancement

#357 add Digibunch
  software/digibunch.yml
Labels: addition

#362 Remove IceHrm (unmaintained since February 2023)
  software/icehrm.yml
Labels: curation

#379 Remove Mahara (the project is archived)
  software/mahara.yml
Labels: bug, curation

#380 typo
  software/paperless-ngx.yml
Labels: bug

#387 remove duplicate entry for otterwiki
  software/otterwiki.yml
Labels: bug

#361 Add OpenTrashmail
  software/open-trashmail.yml
Labels: addition

#363 Add Digiwall
  software/digiwall.yml
Labels: addition

#381 Remove Mango (unmaintained since July 2022)
  software/mango.yml
Labels: curation

#384 Remove Pinedocs (unmaintained since November 2022)
  software/pinedocs.yml
Labels: curation

#391 Remove kcal (unmaintaiend since November 2022)
  software/kcal.yml
Labels: curation

#392 Remove Flextype (unmaintained since November 2022)
  software/flextype.yml
Labels: curation

#403 fix mailpiler homepage URL
  software/piler.yml
Labels: bug

#399 Remove IMP (Unmaintained since 2019)
  software/imp.yml
Labels: curation

#367 Add Zot Registry to File Transfer - Object Storage & File Servers
  software/zotregistry.yml
Labels: addition

#390 add Digimindmap
  software/digimindmap.yml
Labels: addition

#371 Add mikochi to file browsers/media streaming
  software/mikochi.yml
Labels: addition

#398 Add related software to Medusa
  software/medusa.yml
Labels: enhancement
