Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2024-05, with the labels that each got.

#364 Add Digislides
  software/digislides.yml
Labels: addition

#659 feat: add formbricks
  software/formbricks.yml
Labels: addition

#673 Add Pinepods
  software/pinepods.yml
Labels: addition

#689 Remove Phproject (Unmaintained since May 2023, demo down)
  software/phproject.yml
Labels: curation

#695 Remove dotclear website url
  software/dotclear.yml
Labels: bug

#694 Update phplist website
  software/phplist.yml
Labels: bug

#660 Add ocular
  software/ocular.yml
Labels: addition

#680 Add Digimerge
  software/digimerge.yml
Labels: addition

#701 Remove duplicates found in #700
  software/motion-tools.yml
  software/open-slides.yml
  software/tinyfilemanager.yml
  software/zotregistry.yml
Labels: bug

#703 Remove Hawkpost (Unmaintained since April 2023)
  software/hawkpost.yml
Labels: curation, reviewers wanted

#705 Move CASE to Software Development - Low Code
  software/case.yml
Labels: enhancement

#706 Move Appwrite to Software Development - Low Code
  software/appwrite.yml
Labels: enhancement

#707 remove MyPaas (unmaintained since May 2023)
  software/mypaas.yml
Labels: curation

#708 remove PassCheck (unmaintained since May 2023)
  software/passcheck.yml
Labels: curation

#709 remvoe dillinger (unmaintained since May 2023)
  software/dillinger.yml
Labels: curation

#711 Fix typos
  software/actual.yml
  software/coreshop.yml
  software/filestash.yml
  software/nitter.yml
  software/octave-online.yml
  software/ocular.yml
  software/picsur.yml
  software/webtrees.yml
  tags/dns.yml
  tags/file-transfer---single-click--drag-n-drop-upload.yml
Labels: enhancement

#712 Rename VanDAM to Manyfold, and update URLs
  software/manyfold.yml
Labels: curation

#710 remove NATS (already listed at CNCF.io)
  software/nats.yml
Labels: curation

#687 feat: add ente
  software/ente.yml
Labels: addition

#713 remove Homebank-converter (unmaintained since May 2023)
  software/homebank-converter.yml
Labels: curation

#717 move Bracket to Polls and Events
  software/bracket.yml
Labels: enhancement

#720 update bigcapital website
  software/bigcapital.yml
Labels: bug

#721 update opengist demo url
  software/opengist.yml
Labels: bug
