Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2024-12, with the labels that each got.

#964 add SeedDMS
  software/seeddms.yml
Labels: addition

#965 add PdfDing
  software/pdfding.yml
Labels: addition

#973 Create plexripper entry
  software/plexripper
Labels: addition

#974 add Retrom software
  software/retrom.yml
Labels: addition

#983 add HomeBox
  software/homebox-sysadminsmedia.yml
Labels: addition

#987 add: docmost
  software/docmost.yml
Labels: addition

#1005 Fix Piler's source code URL
  software/piler.yml
Labels: bug

#1006 remove duplicate litlyx
  software/litlyx-analytics.yml
Labels: bug

#1011 remove website of eda
  software/eda.yml
Labels: curation

#1009 fix demo of bar assistant
  software/bar-assistant.yml
Labels: bug

#1012 remove website from rygel
  software/rygel.yml
Labels: curation

#1013 add e-book tag to audiobookshelf
  software/audiobookshelf.yml
Labels: enhancement

#1015 Update Kresus' license
  software/kresus.yml
Labels: bug

#1017 Update cal.com.yml license
  software/cal.com.yml
Labels: bug

#1010 remove duet (source code unvailable)
  software/duet.yml
Labels: curation

#1008 remove Padlock (unmaintained since Dec 2023)
  software/padloc.yml
Labels: curation

#996 rename Minetest to Luanti
  software/luanti.yml
  software/minetest.yml
Labels: bug, reviewers wanted

#937 Added Engity's Bifröst
  software/bifroest.yml
Labels: addition

#1021 Remove selenoid (the project is archived)
  software/selenoid.yml
Labels: curation

#1029 remove ass (the project is archived)
  software/ass.yml
Labels: curation

#998 Add iSponsorBlockTV
  software/isponsorblocktv.yml
Labels: addition

#892 Create bugsink.yml
  software/bugsink.yml
Labels: addition, non-free

#982 add BookLogr
  software/booklogr.yml
Labels: addition

#1007 remove osTicket (Unmaintained since Oct 2023)
  software/osticket.yml
Labels: curation, reviewers wanted

#991 Add W software (wiki)
  software/w.yml
Labels: addition

#959 add What to Cook?
  software/whattocook.yaml
Labels: addition

#1000 add slskd
  software/slskd.yml
Labels: addition

#988 Add Donetick
  software/donetick.yml
Labels: addition

#977 add not-th.re
  licenses-nonfree.yml
  software/not-three.yml
Labels: addition, non-free

#990 Add scribble.rs
  software/scribblers.yml
Labels: addition

#992 add YAFFA
  software/yaffa.yml
Labels: addition

#1019 Add Enclosed
  software/enclosed.yml
Labels: addition

#1039 tools/hecat: sort the list of licenses to exclude from the main (Free software) list
  .hecat/export-html.yml
  .hecat/export-markdown.yml
  licenses-nonfree.yml
Labels: tools

#1043 Update anycable source code URL
  software/anycable.yml
Labels: bug

#1045 tools: update hecat to v1.3.1, fix invalid filenames on Windows
  Makefile
  software/what-to-cook.yml
Labels: bug

#1001 add BinPastes to pastebins
  software/binpastes.yml
Labels: addition

#1002 Add Minus Games
  software/minus-games.yml
Labels: addition

#1023 add ezbookkeeping
  software/ezbookkeeping.yml
Labels: addition

#1040 Update the addition issue template
  .github/ISSUE_TEMPLATE/addition.md
Labels: enhancement

#1054 Remove Github stats from Inboxen
  software/inboxen.yml
Labels: bug, curation, reviewers wanted
