Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2024-01, with the labels that each got.

#453 Add Digiboard to Miscellaneous
  software/digiboard.yml
Labels: addition

#419 add Laravel Simple Password Manager
  software/password-manager.yml
Labels: addition

#436 Add GameVault and CC-BY-NC-SA-4.0 license
  .hecat/export-html.yml
  .hecat/export-markdown.yml
  licenses-nonfree.yml
  software/gamevault.yml
Labels: addition, non-free

#461 Fix typo
  software/kavita.yml
Labels: bug

#458 Remove Bibliogram (discontinued)
  software/bibliogram.yml
Labels: curation

#467 Fix Akaunting license
  software/akaunting.yml
Labels: bug

#454 Add Digicard to Miscellaneous
  software/digicard.yml
Labels: addition

#456 Add WikiDocs
  software/wikidocs.yml
Labels: addition

#465 Remove MokinToken (unmaintained since December 2022)
  software/mokintoken.yml
Labels: curation

#470 Remove Spacebin (unmaintained since February 2023)
  software/spacebin.yml
Labels: curation

#484 Fix Demo URL of Uptime Kuma
  software/uptime-kuma.yml
Labels: bug

#488 Move changedetection.io to Automation
  software/changedetection.io.yml
Labels: enhancement, reviewers wanted

#485 Remove MiniNote (unmaintained since January 2023)
  software/mininote.yml
Labels: curation

#499 Update ZOT Registry homepage link
  software/zotregistry.yml
Labels: bug

#478 Add Grocy to Inventory Management
  software/grocy.yml
Labels: enhancement, reviewers wanted

#493 Remove flap (project archived, website down)
  software/flap.yml
Labels: curation

#471 Add Mylar3
  software/mylar3.yml
Labels: addition

#472 Add txtdot
  software/txtdot.yml
Labels: addition

#494 Remove Markdown-Edit (unmaintained since 2021-12-29)
  software/markdown-edit.yml
Labels: curation, reviewers wanted

#495 Remove Minimalist Online Markdown Editor (unmaintained since 2022-09-12)
  software/minimalist-online-markdown-editor.yml
Labels: curation, reviewers wanted

#497 Remove AsciiFlow (unmaintained since 2022-01-15)
  software/asciiflow.yml
Labels: curation, reviewers wanted

#496 Remove QuakeJS (unmaintained since 2022-08-31)
  software/quakejs.yml
Labels: curation, reviewers wanted

#501 Update janus demo url
  software/janus.yml
Labels: bug

#479 Fix Specifically Clementines categories
  software/specifically-clementines.yml
Labels: enhancement, reviewers wanted

#480 Add RecipeSage to Inventory Management
  software/recipesage.yml
Labels: enhancement

#500 doc: contributing: add an 'other guidelines' section for soft guidelines
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation, enhancement

#503 tools: ignore apaxy last update date check
  .hecat/awesome-lint-strict.yml
  .hecat/awesome-lint.yml
Labels: tools, curation

#504 Remove PurritoBin (unmaintained since 2022-04-11)
  software/purritobin.yml
Labels: curation

#507 Update Aimeos source code URL
  software/aimeos.yml
Labels: enhancement

#508 Update Solr source code URL
  software/apache-solr.yml
Labels: enhancement

#509 Update Bitcart source code URL
  software/bitcart.yml
Labels: enhancement

#510 Update BTCPay Server source code URL
  software/btcpay-server.yml
Labels: enhancement

#511 Remove BuddyCloud (unmaintained since 2016)
  software/buddycloud.yml
Labels: curation

#512 Update Bugzilla source Code URL
  software/bugzilla.yml
Labels: enhancement

#513 Remove Cactus Comments (unmaintained since May 2022)
  software/cactus-comments.yml
Labels: curation

#514 Update Calibre Source Code URL
  software/calibre.yml
Labels: enhancement

#445 Add Chibisafe
  software/chibisafe.yml
Labels: addition

#459 add Twenty CRM software
  software/twenty.yml
Labels: addition

#477 Add ybFeed
  software/ybfeed.yml
Labels: addition

#515 Fix easyappointments demo uri
  software/easy!appointments.yml
Labels: bug

#516 Fix gramps-web-api URIs
  software/gramps-web.yml
Labels: bug

#519 Update mediagoblin source code URL
  software/mediagoblin.yml
Labels: enhancement

#522 Remove Gray Duck Mail (unmaintained since Jan 2023)
  software/gray-duck-mail.yml
Labels: curation

#523 Update Copyright on awesome selfhosted website
  .hecat/conf.py
Labels: bug

#524 Update mattermost url
  software/mattermost.yml
Labels: bug

#520 Update sshwifty.yml to add demo url
  software/sshwifty.yml
Labels: enhancement

#528 Fixing Docker for Pi-Hole
  software/pi-hole.yml
Labels: bug

#533 Add Docker to Directus
  software/directus.yml
Labels: enhancement

#535 Removing software "blog" (unmaintained since Jan 2023)
  software/blog.yml
Labels: curation

#537 Adding awstats demo url
  software/awstats.yml
Labels: enhancement, reviewers wanted

#536 Update revolt repository url
  software/revolt.yml
Labels: enhancement

#541 Remove Access to Memory (ATOM) (Source code gone)
  software/access-to-memory-atom.yml
Labels: bug, curation

#469 Add tine
  software/tine.yml
Labels: addition

#544 remove duplicate dify.ai entry
  software/dify.yml
Labels: bug

#545 Fix Tandoor Recipes license
  software/tandoor-recipes.yml
Labels: bug, non-free

#546 Remove Archivematica (source code gone)
  software/archivematica.yml
Labels: bug, curation

#542 doc: PR template: the checklist should only be used for additions
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#547 Remove Demo from Gogs
  software/gogs.yml
Labels: curation

#550 Adding docker tag for anonaddy
  software/anonaddy.yml
Labels: enhancement

#549 Remove activeworkflow (unmaintained since April 2023)
  software/activeworkflow.yml
Labels: curation

#540 Fix EDA license & stack
  software/eda.yml
Labels: bug
