Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2024-07, with the labels that each got.

#759 Add Hatsu
  software/hatsu.yml
Labels: addition

#760 Add OpenTTD to Games
  software/openttd.yml
Labels: addition

#768 Remove Solidus demo
  software/solidus.yml
Labels: curation

#769 Fix tryton
  software/tryton.yml
Labels: curation

#767 Remove easyshortener
  software/easyshortener.yml
Labels: curation

#766 fix hitobito website
  software/hitobito.yml
Labels: curation

#765 Remove Seatsurfing demo
  software/seatsurfing.yml
Labels: curation, reviewers wanted

#773 Remove Metronome IM (unmaintained since 2023-07-08)
  software/metronome-im.yml
Labels: curation

#774 Remove Teeworlds (unmaintained since 2023-06-29)
  software/teeworlds.yml
Labels: curation, reviewers wanted

#775 Remove OvenMediaEngine website
  software/ovenmediaengine.yml
Labels: bug

#783 Remove passwall (Unmaintained since July 2023)
  software/passwall.yml
Labels: curation, reviewers wanted

#780 Added the demo URL for CommaFeed
  software/commafeed.yml
Labels: enhancement, reviewers wanted

#758 Add Hoarder App
  software/hoarder-app.yml
Labels: addition

#762 Add Meelo
  software/meelo.yml
Labels: addition

#692 Add E-Label
  software/e-label.yml
Labels: addition

#764 Add Fusion
  software/fusion.yml
Labels: addition
