Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2024-02, with the labels that each got.

#555 Update Demo of ArchivesSpace
  software/archivesspace.yml
Labels: bug

#561 merge duplicate opentrashmail entries
  software/open-trashmail.yml
  software/opentrashmail.yml
Labels: bug

#462 Add CASE
  software/case.yml
Labels: addition

#548 Add HoloPlay to Media/Audio Streaming
  software/holoplay.yml
Labels: addition

#567 Remove PropertyWebBuilder (unmaintained since Feb 2023)
  software/propertywebbuilder.yml
Labels: curation

#573 Update bracket
  software/bracket.yml
Labels: bug

#575 Remove Pairdrop (Project deleted)
  software/pairdrop.yml
Labels: curation

#572 Remove MailForm (unmaintained since Feb 16, 2023)
  software/mailform.yml
Labels: curation

#564 Add SparkView to Remote Access
  software/sparkview.yml
Labels: addition, non-free

#558 Add bitmagnet
  software/bitmagnet.yml
Labels: addition

#580 Remove Journal (unmaintained since Feb 2023)
  software/journal.yml
Labels: curation

#584 remove comment of OpenTrashmail
  software/opentrashmail.yml
Labels: bug

#590 Remove Hasty Paste (Archived)
  software/hasty-paste.yml
Labels: curation

#589 Remove ViMbAdmin (Unmaintained since February 2023)
  software/vimbadmin.yml
Labels: curation

#570 Add Jauth to Proxy
  software/jauth.yml
Labels: addition

#576 Add Chhoto URL
  software/chhoto-url.yml
Labels: addition

#578 Add FeedCord
  software/feedcord.yml
Labels: addition

#592 Update kimai license
  software/kimai.yml
Labels: bug
