Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2024-04, with the labels that each got.

#604 add `OpenSlides` as conference software
  software/open-slides.yml
Labels: addition

#611 Add Receipt Wrangler
  software/receipt-wrangler.yml
Labels: addition

#618 Added Panora
  software/panora.yml
Labels: addition

#629 Add kyoo
  software/kyoo.yml
Labels: addition

#634 Add tinyfilemanager
  software/tinyfilemanager.yml
Labels: addition

#615 Add ryot
  software/ryot.yml
Labels: addition

#643 Fix pretix metadata
  software/pretix.yml
Labels: enhancement

#652 doc: add liberapay badge alongside other badges
  README.md
  markdown/header.md
Labels: documentation, tools

#654 Update wikipedia link on URL shorteners
  tags/url-shorteners.yml
Labels: bug

#406 Add OpenSign™
  software/opensign.yml
Labels: addition

#627 add `motion.tools` as conference software
  software/motion-tools.yml
Labels: addition

#633 Add litecart to E-Commerce
  software/litecart.yml
Labels: addition

#655 Remove Mailcare (unmaintained since sept 2023, new versions are proprietary)
  software/mailcare.yml
Labels: curation, non-free

#651 Add platform to Erxes
  software/erxes.yml
Labels: enhancement

#661 Update Kavita demo
  software/kavita.yml
Labels: bug

#662 Remove Pastr (unmaintained since Dec 2023, demo link down, no releases)
  software/pastr.yml
Labels: curation, reviewers wanted

#665 Remove duplicate "Laravel simple password manager" entry
  software/password-manager.yml
Labels: bug

#667 Update immich license
  software/immich.yml
Labels: bug

#668 Remove My Mind (Unmaintained since April 2023)
  software/my-mind.yml
Labels: curation

#645 Add HortusFox to Miscellaneous
  software/hortusfox.yml
Labels: addition

#646 Add Readeck to Bookmarks & Link Sharing / Archiving & DP
  software/readeck.yml
Labels: addition

#647 Add Digitranscode to Miscellaneous
  software/digitranscode.yml
Labels: addition

#650 Add multi-scrobbler
  software/multi-scrobbler.yml
Labels: addition

#656 add schoco
  software/schoco.yml
Labels: addition

#670 Remove Manage My Damn Live website URL
  software/manage-my-damn-life.yml
Labels: bug

#671 Remove rgit demo URL
  software/rgit.yml
Labels: bug

#672 Update Slimta website URL
  software/slimta.yml
Labels: bug

#657 Adding EverShop to the E-commerce software list
  software/evershop.yml
Labels: addition

#675 Update digitranscode.yml
  software/digitranscode.yml
Labels: bug

#678 Remove Podify (Unmaintained since April 2023)
  software/podify.yml
Labels: curation

#682 Update Demo URL of Ryot
  software/ryot.yml
Labels: bug

#681 Remove envlinks (Unmaintained since April 2023)
  software/envlinks.yml
Labels: curation

#663 Add Mafl
  software/mafl.yml
Labels: addition
