Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2024-08, with the labels that each got.

#795 Remove Laravel Simple Password Manager (Archived)
  software/laravel-simple-password-manager.yml
Labels: curation

#801 Remove sheetable (Unmaintained since Jul 2023)
  software/sheetable.yml
Labels: curation

#799 Remove MicroBin (Unmaintained since Jul 2023)
  software/microbin.yml
Labels: curation

#798 Remove Hound (Unmaintained since Jul 2023)
  software/hound.yml
Labels: curation

#797 Change EPrints repo to supported version
  software/eprints.yml
Labels: bug

#796 Remove Drift (Unmaintained since Jul 2023)
  software/drift.yml
Labels: curation

#800 Exclude POMjs from awesome_lint activity check
  .hecat/awesome-lint-strict.yml
  .hecat/awesome-lint.yml
Labels: curation

#789 Move DOCAT to Miscellaneous
  software/docat.yml
Labels: curation

#793 Update spree commerce demo URL
  software/spree-commerce.yml
Labels: bug, reviewers wanted

#784 Add Puter
  software/puter.yml
Labels: addition

#782 Add Spacebin
  software/spacebin.yml
Labels: addition

#777 Add CxReports
  software/cxreports.yml
Labels: addition, non-free

#770 Add portkey
  software/portkey.yml
Labels: addition

#787 Add Viseron
  software/viseron.yaml
Labels: addition

#814 move Web Servers/Reverse Proxies back from awesome-sysadmin
  software/algernon.yml
  software/apache.yml
  software/caddy.yml
  software/cosmos.yml
  software/haproxy.yml
  software/jauth.yml
  software/lighttpd.yml
  software/nginx-proxy-manager.yml
  software/nginx.yml
  software/pomerium.yml
  software/static-web-server.yml
  software/swag-secure-web-application-gateway.yml
  software/traefik.yml
  software/varnish.yml
  tags/proxy.yml
  tags/web-servers.yml
Labels: enhancement, addition

#816 Remove PoeticMetric (unmaintained since 2023-08-11)
  software/poeticmetric.yml
Labels: curation, reviewers wanted

#679 add BunkerWeb
  software/bunkerweb.yml
Labels: addition

#807 Add Tamari
  software/tamari.yml
Labels: addition

#832 Fix tryton demo link
  software/tryton.yml
Labels: bug

#833 Fix kubek website url
  software/kubek.yml
Labels: bug

#834 Remove paperspace (Unmaintained since Oct 2021)
  software/paper{s}pace.yml
Labels: curation, reviewers wanted

#810 add Prisme Analytics
  software/prisme-analytics.yml
Labels: addition

#820 Add MyIP to awesome selfhosted
  software/myip.yml
Labels: addition
