Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2024-03, with the labels that each got.

#595 Remove Demo URL for JAuth
  software/jauth.yml
Labels: bug

#597 Remove Zot Registry Duplicate
  software/zot-oci-registry.yml
Labels: curation

#602 Fix Daneecloud (404. Login required for demo)
  software/daneecloud.yml
Labels: bug

#583 Add Huly Platform
  software/huly.yml
Labels: addition

#587 Add gathio
  software/gathio.yml
Labels: addition

#588 Add Grimoire bookmark manager
  software/grimoire.yml
Labels: addition

#605 Remove Wordle (source code gone)
  software/wordle.yml
Labels: bug, curation

#606 Fix shopware (Old 404 link)
  software/shopware-community-edition.yml
Labels: bug

#616 remove FlaskBB (unmaintained since Mar 13 2023)
  software/flaskbb.yml
Labels: curation

#617 Remove short{paste} (unmaintained since 13 March 2023)
  software/short{paste}.yml
Labels: curation

#622 Remove cmyflix (unmaintained since March 2023)
  software/cmyflix.yml
Labels: curation

#621 Remove Cloudbox (unmaintained since March 2023)
  software/cloudbox.yml
Labels: curation

#613 add Tube Archivist
  software/tubearchivist.yml
Labels: addition

#626 Update CloudBeaver URL
  software/cloudbeaver.yml
Labels: bug

#585 add beelzebub.yml
  software/beelzebub.yml
Labels: addition

#631 Update VLC source code link
  software/videolan-client-vlc.yml
Labels: bug

#632 Remove duplicate Tube Archivist entry
  software/tubearchivist.yml
Labels: bug
