Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2024-10, with the labels that each got.

#882 Remove Temboz (Unmaintained since Sep 2023)
  software/temboz.yml
Labels: curation

#873 Create invoiceshelf.yml
  software/invoiceshelf.yml
Labels: addition

#869 Create artalk.yml
  software/artalk.yml
Labels: addition

#866 Add Hi.Events Software
  software/hi-events.yml
Labels: addition

#865 add Jelu
  software/jelu.yml
Labels: addition

#860 add Dittofeed
  software/dittofeed.yml
Labels: addition

#885 Delete software/lubelog.yml
  software/lubelog.yml
Labels: bug

#886 remove Stalwart JMAP/SMTP (the project is archived)
  software/stalwart-jmap.yml
  software/stalwart-smtp.yml
Labels: bug

#889 add HedgeDoc demo
  software/hedgedoc.yml
Labels: enhancement

#890 Remove Vigil (unmaintained since Oct 9, 2023)
  software/vigil.yml
Labels: curation

#836 Added Cloud Seeder
  software/cloud-seeder.xml
Labels: addition, non-free

#876 Add HTMLy
  software/htmly.yml
Labels: addition

#879 Add Langfuse
  software/langfuse.yml
Labels: addition

#899 remove lufi demo
  software/lufi.yml
Labels: curation

#900 update The Epube homepage/source code URL
  software/the-epube.yml
Labels: curation

#915 Remove viseron (duplicate entry)
  software/viseron.yaml
Labels: bug, reviewers wanted

#850 Add bewCloud
  software/bewcloud.yml
Labels: addition

#883 Add GlobaLeaks Whistleblowing Software
  software/globaleaks.yml
Labels: addition

#894 Add OpnForm
  software/opnform.yml
Labels: addition

#903 Create ui-bakery.yml
  software/ui-bakery.yml
Labels: addition, non-free

#926 doc: CONTRIBUTING: add premade reply for projects without releases
  CONTRIBUTING.md
Labels: documentation

#924 Remove duplicated entry
  software/hi-events.yml
Labels: bug

#895 Add Maybe
  software/maybe.yml
Labels: addition

#916 remove LBRY (unmaintained since 2023-10-23)
  software/lbry.yml
Labels: curation
