Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2024-06, with the labels that each got.

#728 Mark Wikis tag as related to Knowledge Management Tools
  tags/wikis.yml
Labels: enhancement

#727 Mark Wikis tag as related to Note-taking & Editors
  tags/wikis.yml
Labels: enhancement

#726 remove Mibew (unmaintained since May 2023)
  software/mibew.yml
Labels: curation

#725 Add Groupware tag to Nextcloud
  software/nextcloud.yml
Labels: enhancement

#737 Remove onTrack (the project is archived)
  software/ontrack.yml
Labels: bug, curation

#739 doc: issue template: cleanup/don't repeat contributing.md
  .github/ISSUE_TEMPLATE/addition.md
Labels: documentation

#744 remove httprd (unmaintained since June 2023)
  software/httprd.yml
Labels: curation

#742 Remove Kanbana (Unmaintained since June 2023)
  software/kanbana.yml
Labels: curation, reviewers wanted

#747 remove eonza (unmaintained since June 2023)
  software/eonza.yml
Labels: curation

#724 Add Feather Wiki
  software/feather-wiki.yml
Labels: addition

#730 Add minimal-git-server
  software/minimal-git-server.yml
Labels: addition

#751 Remove Homebox Inventory (archived project)
  software/homebox-inventory.yml
Labels: bug, curation

#752 fix otobo
  software/otobo.yml
Labels: curation

#755 Remove stalwart-smtp website
  software/stalwart-smtp.yml
Labels: curation

#754 Remove stalwart-jmap website
  software/stalwart-jmap.yml
Labels: curation

#753 Remove Open Commerce (Unmaintained since June 2023)
  software/mailchimp-open-commerce.yml
Labels: curation

#674 Create qst.yml for #574
  software/qst.yml
Labels: addition

#729 Add Wavelog
  software/wavelog.yml
Labels: addition

#734 Add Dagu to Automation
  software/dagu.yml
Labels: addition

#735 Add PartDB to Inventory Management
  software/partdb.yml
Labels: addition

#749 Add AnyCable
  software/anycable.yml
Labels: addition

#683 Add Hook0
  software/hook0.yml
Labels: addition, non-free

#761 Remove LibreX (Unmaintained since June 2023)
  software/librex.yml
Labels: curation

#763 Delete software/partdb.yml duplicate with software/part-db.yml (#1)
  software/partdb.yml
Labels: bug
