Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2024-11, with the labels that each got.

#930 remove anahita (unmaintained since oct 2023)
  software/anahita.yml
Labels: curation

#931 remove hmailserver (unmaintained since oct 2023)
  software/hmailserver.yml
Labels: curation

#932 Remove fathom-lite (unmaintained since oct 2023)
  software/fathom-lite.yml
Labels: curation

#933 remove demo from gosé
  software/gosɛ.yml
Labels: curation

#906 Add DiscountBandit to Automation & E-Commerce
  software/discountbandit.yml
Labels: addition

#907 Add Handbrake Web to Automation
  software/handbrakeweb.yml
Labels: addition

#913 Create open-quartermaster.yml
  software/open-quartermaster.yml
Labels: addition

#944 Remove handbrakeweb (duplicate)
  software/handbrakeweb.yml
Labels: bug

#881 To add software beaver habtit tracker
  software/beaverhabits.yml
Labels: addition

#893 add Learning software
  software/scholarsome.yml
Labels: addition

#902 Add Vvveb CMS software
  software/vvveb.yml
Labels: addition

#908 Create github-ntfy.yml
  software/github-ntfy.yml
Labels: addition

#917 Add Cannery
  software/cannery.yml
Labels: addition

#923 Add Lesma to Pastebins
  software/lesma.yml
Labels: addition

#939 Add LibreKB to Knowledge Management
  software/librekb.yml
Labels: addition

#949 Remove benotes (unmaintained since Nov 4 2023)
  software/benotes.yml
Labels: curation

#950 Remove Dada Mail (unmaintained since Nov 6 2023)
  software/dada-mail.yml
Labels: curation

#951 Remove Nitter (unmaintained since Oct 31 2023)
  software/nitter.yml
Labels: curation

#952 tools: exclude nullboard from activity check
  .hecat/awesome-lint-strict.yml
  .hecat/awesome-lint.yml
Labels: tools, curation

#953 Remove Oblecto (unmaintained since Nov 2, 2023)
  software/oblecto.yml
Labels: curation

#960 remove dendrite (the project is archived)
  software/dendrite.yml
Labels: curation

#963 Remove cloud-seeder.xml from /software
  software/cloud-seeder.xml
Labels: bug

#962 Removed Exadel Compreface (unmaintained since Nov 2023)
  software/exadel-compreface.yml
Labels: curation

#961 Remove Orange Forum (unmaintained since Nov 2023)
  software/orange-forum.yml
Labels: curation

#808 Add software “solidtime”
  software/solidtime.yml
Labels: addition

#935 Adds AdventureLog
  software/adventurelog.yml
Labels: addition

#968 remove duplicate entries
  software/beaverhabits.yml
  software/discountbandit.yml
  software/pelicanpanel.yml
  software/vvveb.yml
Labels: bug

#981 remove infinoted (unmaintained since Nov 2023)
  software/infinoted.yml
Labels: curation

#980 Update Gitea with recent demo site link and description from official site
  software/gitea.yml
Labels: enhancement

#943 add Litlyx analytics
  software/litlyx-analytics.yml
Labels: addition

#947 add LidaTube
  software/lidatube.yml
Labels: addition

#878 add SiYuan
  software/siyuan.yml
Labels: addition

#989 fix Romm tags
  software/romm.yml
Labels: bug
