Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2024-09, with the labels that each got.

#841 Remove Blink (Unmaintained since Aug 2023)
  software/blink.yml
Labels: curation

#846 Fix asciinema URL and Demo
  software/asciinema.yml
Labels: bug

#826 Add auto-mcs
  software/auto-mcs.yml
Labels: addition

#827 Add Photofield
  software/photofield.yml
Labels: addition

#828 Add LubeLogger
  software/lubelog.yml
Labels: addition

#830 Add Recipya
  software/recipya.yml
Labels: addition

#831 Add PodFetch
  software/podfetch.yml
Labels: addition

#855 Remove LeapChat (Unmaintained since Sep 2023)
  software/leapchat.yml
Labels: curation

#854 Remove LazyLead (Unmaintained since Sep 2023)
  software/lazylead.yml
Labels: curation

#815 Added Silverbullet note taking app
  software/silverbullet.yml
Labels: addition

#859 Fix 0-a.d. (Project archived in GitHub)
  software/0-a.d..yml
Labels: bug

#867 remove YetiForce (archived, now proprietary)
  software/yetiforce.yml
Labels: bug, curation, non-free

#843 Add Precis
  software/precis.yml
Labels: addition

#844 Add HeyForm to Polls and Events
  software/heyform.yml
Labels: addition

#847 Added redlib
  software/redlib.yml
Labels: addition

#851 Add Immich Kiosk
  software/immich-kiosk.yml
Labels: addition

#863 Delete kerberos.io NVR
  software/kerberos.io.yml
Labels: bug, curation, non-free

#741 Add Pelican Panel to Games - Admin Utilities & Control Panels
  software/pelicanpanel.yml
Labels: addition, reviewers wanted

#857 add conduwuit
  software/conduwuit.yml
Labels: addition

#858 Add glance.yml
  software/glance.yml
Labels: addition

#870 tools: Update github actions/checkout to latest version
  .github/workflows/build.yml
  .github/workflows/check-dead-links.yml
  .github/workflows/check-unmaintained-projects.yml
  .github/workflows/daily-update-metadata.yml
  .github/workflows/pull-request.yml
Labels: tools

#872 fix: coppermine-gallery has migrated
  software/coppermine.yml
Labels: bug

#849 Edit MistServer license and description
  software/mistserver.yml
Labels: bug
