Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2025-08, with the labels that each got.

#1554 Remove OrangeHRM (unmaintained since Jul 2024)
  software/orangehrm.yml
Labels: curation, reviewers wanted

#1552 Remove YABin (unmaintained since Jul 2024)
  software/yabin.yml
Labels: curation, reviewers wanted

#1489 Add Booklore to Document Management - Ebooks
  software/booklore.yml
Labels: addition

#1503 Add Kaneo to Software Development - Project Management
  software/kaneo.yml
Labels: addition

#1505 Add Flare to the list
  software/flare.yml
Labels: addition

#1563 update links to staticsitegenerators.net -> staticsitegenerators.bevry.me
  .github/ISSUE_TEMPLATE/addition.md
  .github/PULL_REQUEST_TEMPLATE.md
  tags/static-site-generators.yml
Labels: bug, documentation, curation, reviewers wanted

#1571 Remove Demo from GeneWeb
  software/geneweb.yml
Labels: curation

#1572 Remove Demo from LedgerSMB
  software/ledgersmb.yml
Labels: curation

#1574 Remove JSXC (Unmaintained since Aug 2024)
  software/jsxc.yml
Labels: curation, reviewers wanted

#1587 fix screenconnect url
  software/screenconnect.yml
Labels: curation

#1564 Add Drop to Games - Admin Utilities & Control Panels
  software/drop.yml
Labels: addition

#1567 Add Ziit
  software/ziit.yml
Labels: addition

#1595 Add alternative frontends to footer.md
  markdown/footer.md
Labels: documentation, reviewers wanted

#1612 update source code URLs
  software/acp-admin.yml
  software/answer.yml
  software/atsumeru.yml
  software/black-candy.yml
  software/blinko.yml
  software/booklore.yml
  software/eclipse-che.yml
  software/element.yml
  software/flowforge.yml
  software/focalboard.yml
  software/freescout.yml
  software/globaleaks.yml
  software/inginious.yml
  software/isso.yml
  software/jina.yml
  software/mataroa.yml
  software/mathesar.yml
  software/mejiro.yml
  software/qloapps.yml
  software/reaparr.yml
  software/seatsurfing.yml
  software/shopware-community-edition.yml
  software/sist2.yml
  software/slash.yml
  software/stalwart-mail-server.yml
  software/stirling-pdf.yml
  software/suitecrm.yml
  software/swingmusic.yml
  software/teslamate.yml
  software/tiddlywiki.yml
  software/tipi.yml
  software/txtdot.yml
  software/wildduck.yml
  software/workadventure.yml
  software/yt-dlp-web-ui.yml
Labels: curation
