Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2025-06, with the labels that each got.

#1415 Update URLs for Mergeable
  software/mergeable.yml
Labels: enhancement

#1425 Adjusting cozycloud description and add related software
  software/cozy-cloud.yml
Labels: bug

#1421 added archiving tag to paperless
  software/paperless-ngx.yml
Labels: bug

#1240 Add G3Proxy to Proxy
  software/g3proxy.yml
Labels: addition

#1419 Added anythingllm to AI
  software/anythingllm.yml
Labels: addition

#1420 Add AFFiNE to Knowledge Management Tools
  software/affine-community-edition.yml
Labels: addition

#1424 Add Chiyogami
  software/chiyogami.yml
Labels: addition

#1452 Add homer demo url
  software/homer.yml
Labels: bug

#1451 Update druid website url
  software/druid.yml
Labels: bug

#1443 Update github ntfy
  software/github-ntfy.yml
Labels: bug

#1407 Add Paperless-AI to the Awesome Selfhosted List
  software/paperless-ai.yml
Labels: addition

#1449 Remove Mars Server (Unmaintained since June 2024)
  software/mars-server.yml
Labels: curation, reviewers wanted

#1448 Remove HRConvert2 (Unmaintained since June 2024)
  software/hrconvert2.yml
Labels: curation, reviewers wanted

#1447 Remove Coppermine (Unmaintained since June 2024)
  software/coppermine.yml
Labels: curation, reviewers wanted

#1453 Update send
  software/send.yml
Labels: bug

#1462 Update source code / website url for trilium notes
  software/triliumnext-notes.yml
Labels: curation
