Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2025-02, with the labels that each got.

#1131 remove inlets (unmaintained since jan 2024)
  software/inlets.yml
Labels: curation

#1129 Update not-th.re: License Changed
  software/not-th.re.yml
Labels: bug

#1136 update website_url of HedgeDoc
  software/hedgedoc.yml
Labels: bug

#1035 Add bookbounty.yml
  software/bookbounty.yml
Labels: addition

#1096 Add AirTrail
  software/airtrail.yml
Labels: addition

#1033 Adding lidify.yml
  software/lidify.yml
Labels: addition

#1022 add ghstats
  software/ghstats.yml
Labels: addition

#1111 Add Wakupator
  software/wakupator.yml
Labels: addition

#1095 add SAMA chat platform
  software/sama.yml
Labels: addition

#1121 add kener
  software/kener.yml
Labels: addition

#1140 Update uptime-kuma.yml website url
  software/uptime-kuma.yml
Labels: bug

#1147 Update Actual source code URL
  software/actual.yml
Labels: bug

#1124 Add WebhookTester
  software/webhook-tester.yml
Labels: addition

#722 Add dropserver
  software/dropserver.yml
Labels: addition

#1138 add Frappe HR
  software/frappe-hr.yml
Labels: addition

#1139 add MintHCM
  software/minthcm.yml
Labels: addition

#1153 doc: issue template: update link to awesome-syadmin in addition.md
  .github/ISSUE_TEMPLATE/addition.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#1152 remove devicehive (Unmaintained since Feb 2024)
  software/devicehive.yml
Labels: curation

#1159 remove Lynx (project archived)
  software/lynx.yml
Labels: curation

#1161 remove instant.io (unmaintained since Feb 2024)
  .hecat/url-check.yml
  software/instant.io.yml
Labels: curation
