Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2025-03, with the labels that each got.

#1166 remove Budget Zen (project archived)
  software/budget-zen.yml
Labels: curation

#1165 remove kchat (unmaintained since Feb 2024 & Vuln)
  software/kchat.yml
Labels: curation

#1163 remove Loggit (project archived)
  software/loggit.yml
Labels: curation

#1164 remove EteSync (unmaintained since Feb 2024)
  software/etesync-web.yml
Labels: curation

#1118 Add ManageMeals
  software/managemeals.yml
Labels: addition

#1141 add Wallos software
  software/wallos.yml
Labels: addition

#1144 add Liwan
  software/liwan.yml
Labels: addition

#1146 add self-host-blocks
  software/self-host-blocks.yml
Labels: addition

#1162 re-add Adminer
  software/adminer.yml
Labels: addition

#1128 add bit
  software/bit.yml
Labels: addition

#1169 fix: update homarr repository
  software/homarr.yml
Labels: bug

#1172 Remove Iguana (Unmaintained since Feb 2024)
  software/iguana.yml
Labels: curation

#1182 fix dspace website url
  software/dspace.yml
Labels: bug

#1181 remove demo from mathesar
  software/mathesar.yml
Labels: curation

#1176 remove open streaming platform (project archived)
  software/open-streaming-platform.yml
Labels: curation

#1179 remove demo from enigma-12-bbs
  software/enigma-12-bbs.yml
Labels: curation

#1178 remove WikiDocs demo
  software/wikidocs.yml
Labels: curation

#1177 update website of pimcore
  software/pimcore.yml
Labels: bug

#1184 Update MyFin after soft rebrand
  software/myfin-budget.yml
Labels: bug

#1156 add Websoft9
  software/websoft9.yml
Labels: addition

#1160 Create go-proxy.yml
  software/go-doxy.yml
Labels: addition

#1137 Add Livecodes to Software Development - IDE & Tools
  software/livecodes.yml
Labels: addition

#1058 Add memEx
  software/memex.yml
Labels: addition

#945 add clipcascade
  software/clipcascade.yml
Labels: addition

#1185 Remove Timeoff Management (Unmaintained since Jan 2024)
  software/timeoff.management.yml
Labels: curation

#1192 Remove ARRCON (Unmaintained since March 2024)
  software/arrcon.yml
Labels: curation

#1195 Remove Fileshelter (Unmaintaied since March 2024)
  software/fileshelter.yml
Labels: curation

#1194 Fix URLs and checks
  .hecat/url-check.yml
  software/flexisip.yml
  software/zentao.yml
Labels: curation

#1020 Add shkeeper.yml
  software/shkeeper.yml
Labels: addition

#1171 (re-)add pacebin
  software/pacebin.yml
Labels: addition

#1167 include flink URL shortener
  software/flink.yml
Labels: addition

#1199 Remove Touca (Unmaintained since March 2024)
  software/touca.yml
Labels: curation

#1198 Remove Meemo (Unmaintained since March 2024)
  software/meemo.yml
Labels: curation

#1197 Remove Bepasty (Unmaintained since March 2024)
  software/bepasty.yml
Labels: curation

#1204 Fix source code url for apache http server
  software/apache-http-server.yml
Labels: curation

#1205 fix build error
  software/standard-notes.yml
Labels: bug

#1174 Add TrailBase.
  software/trailbase.yml
Labels: addition

#1190 Add WYGIWYH
  software/wygiwyh.yml
Labels: addition

#1188 add Endurain
  software/endurain.yml
Labels: addition

#1186 add wanderer
  software/wanderer.yml
Labels: addition

#1187 add ConvertX
  software/convertx.yml
Labels: addition

#1183 (re-)add clink
  software/clink.yml
Labels: addition

#1191 add AliasVault
  software/aliasvault.yml
Labels: addition

#1216 remove domainMOD
  software/domainmod.yml
Labels: curation

#1217 remove cerbos
  software/cerbos.yml
Labels: curation

#1220 Remove COD (Unmaintained since Jan 2024)
  .hecat/url-check.yml
  software/conference-organizing-distribution-cod.yml
Labels: curation

#1218 Add links to url-check
  .hecat/url-check.yml
  software/dashpress.yml
  software/elixire.yml
  software/mobilizon.yml
  software/ofbiz.yml
Labels: curation

#1229 Updated CONTRIBUTING.md: improved language
  CONTRIBUTING.md
  Makefile
Labels: documentation, reviewers wanted

#1208 Add TrueConf
  software/trueconf.yml
Labels: addition, non-free

#1232 Add CRM tag
  software/chaskiq.yml
  software/corteza.yml
  software/dolibarr.yml
  software/espocrm.yml
  software/krayin.yml
  software/monica.yml
  software/suitecrm.yml
  software/twenty.yml
  tags/customer-relationship-management-crm.yml
Labels: enhancement, reviewers wanted

#1242 Adjust Trueconf's Website URL
  software/trueconf.yml
Labels: bug

#1233 Remove Soketi (Unmaintained since March 2024)
  software/soketi.yml
Labels: curation

#1243 Remove Open Event Server (Unmaintained since March 2024)
  software/open-event-server.yml
Labels: curation

#1244 Remove Textbelt (Unmaintained since March 2024)
  software/textbelt.yml
Labels: curation

#1248 tools: update hecat to v1.4.0
  Makefile
Labels: bug, tools

#1250 Fix txtdot Website Link (404)
  software/txtdot.yml
Labels: curation

#1101 Add Kutt, a modern URL shortener
  software/kutt.yml
Labels: addition

#1224 add Pinchflat
  software/pinchflat.yml
Labels: addition

#1223 add Gaseous Server
  software/gaseous-server.yml
Labels: addition

#1222 add Speedtest Tracker
  software/speedtest-tracker.yml
Labels: addition

#1256 Update WYGIWYH
  software/wygiwyh.yml
Labels: bug

#1257 Update NGINX repository
  software/nginx.yml
Labels: bug
