Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2025-04, with the labels that each got.

#1237 Add Feature Toggle Tag
  software/flagsmith.yml
  software/go-feature-flag.yml
  software/posthog.yml
  tags/software-development---feature-toggle.yml
  tags/software-development.yml
Labels: enhancement

#1241 Add Docs to Note-Taking & KMS
  software/docs.yml
Labels: addition

#1245 add Yamtrack
  software/yamtrack.yml
Labels: addition

#1247 add Documenso
  software/documenso.yml
Labels: addition

#1271 Remove Hakatime (Unmaintained since April 2024)
  software/hakatime.yml
Labels: curation

#1272 remove Strema (Unmaintained since April 2024)
  software/streama.yml
Labels: curation

#1274 Update website dashy.yml
  software/dashy.yml
Labels: bug

#1279 Move Flipt to Feature Toggle
  software/flipt.yml
Labels: bug

#1275 Remove Dalton Plan (Unmaintained since Aug 2024, On Hold)
  software/dalton-plan.yml
Labels: curation

#1276 Remove Lufi (Unmaintained since December 2023)
  software/lufi.yml
Labels: curation

#1235 Add davmail to Communication - Email MTA
  software/davmail.yml
Labels: addition

#1236 Add Fork Recipes to Recipe Management
  software/fork-recipes.yml
Labels: addition

#1238 Add Featbit
  software/featbit.yml
Labels: addition

#1246 add Reiverr
  software/reiverr.yml
Labels: addition

#1263 Add ExpenseOwl
  software/expenseowl.yml
Labels: addition

#1266 Add blinko
  software/blinko.yml
Labels: addition

#1267 Add Local Content Share
  software/local-content-share.yml
Labels: addition

#1260 Add forwardemail to Email - Complete Solutions
  software/forward-email.yml
Labels: addition, non-free

#1285 Remove Wantgunsbin (Unmaintained since April 2024)
  software/wantgunsbin.yml
Labels: curation

#1291 Remove conduwuit (Project archived)
  software/conduwuit.yml
Labels: curation

#1290 Remove Frab (Unmaintained since April 2024)
  software/frab.yml
Labels: curation

#1286 Update project descriptions starting with A
  software/0-a.d..yml
  software/2fauth.yml
  software/accent.yml
  software/activitywatch.yml
  software/actual.yml
  software/adguard-home.yml
  software/admidio.yml
  software/aimeos.yml
  software/airtrail.yml
  software/akaunting.yml
  software/alerthub.yml
  software/alf.io.yml
  software/anchr.yml
  software/anonaddy.yml
  software/answer.yml
  software/apache-airflow.yml
  software/appflowy.yml
  software/appsmith.yml
  software/aptabase.yml
  software/archivebox.yml
  software/artalk.yml
  software/asmbb.yml
  software/atsumeru.yml
  software/audiobookshelf.yml
  software/azuracast.yml
Labels: enhancement, curation

#1296 General clean up of projects beginning with B.
  software/baby-buddy.yml
  software/bar-assistant.yml
  software/beelzebub.yml
  software/bencher.yml
  software/bewcloud.yml
  software/bigcapital.yml
  software/bigtree-cms.yml
  software/bit.yml
  software/bitbucket-server.yml
  software/bitcart.yml
  software/bitmagnet.yml
  software/bitpoll.yml
  software/bitwarden.yml
  software/black-candy.yml
  software/blocky.yml
  software/bludit.yml
  software/booklogr.yml
  software/bookstack.yml
  software/bracket.yml
  software/btcpay-server.yml
  software/bubo-reader.yml
  software/buku.yml
Labels: enhancement, curation

#1297 fix Media Management tag syntax
  tags/media-streaming.yml
Labels: bug

#1301 Remove Sorry Cypress (Unmaintained since April 2024)
  software/sorry-cypress.yml
Labels: curation

#1305 remove slimta (Unmaintained since April 2024)
  software/slimta.yml
Labels: curation

#1309 tags: fix Generative Artificial Intelligence (GenAI) description
  tags/generative-ai.yml
Labels: bug

#1292 add Zoraxy
  software/zoraxy.yml
Labels: addition

#1293 add MySpeed
  software/myspeed.yml
Labels: addition

#1294 add slink
  software/slink.yml
Labels: addition

#1299 General clean up of projects beginning with C
  software/cal.com.yml
  software/calibre-web.yml
  software/canvas-lms.yml
  software/casaos.yml
  software/castopod.yml
  software/cgit.yml
  software/chamilo-lms.yml
  software/changedetection.io.yml
  software/chartbrew.yml
  software/chatwoot.yml
  software/chirpy.yml
  software/chitchatter.yml
  software/ckan.yml
  software/cloud-seeder.yml
  software/cloudbeaver.yml
  software/cloudlog.yml
  software/cms-made-simple.yml
  software/cncjs.yml
  software/cockpit.yml
  software/contao.yml
  software/converse.js.yml
  software/coppermine.yml
  software/coreshop.yml
  software/corteza.yml
  software/cosmos.yml
  software/couchcms.yml
  software/countly-community-edition.yml
  software/crafty-controller.yml
  software/cryptpad.yml
  software/cytube.yml
Labels: enhancement, curation

#1317 Remove Dat Project (Unmaintained organisation)
  software/dat-project.yml
Labels: curation

#1316 Remove Organizr (Unmaintained since April 2024)
  software/organizr.yml
Labels: curation

#1318 General clean up of projects beginning with D, E and F
  software/datasette.yml
  software/dify.ai.yml
  software/discount-bandit.yml
  software/domjudge.yml
  software/drupal-commerce.yml
  software/easy!appointments.yml
  software/emqx.yml
  software/enclosed.yml
  software/erpnext.yml
  software/etherpad.yml
  software/everydocs.yml
  software/evidence.yml
  software/fasten-health.yml
  software/fava.yml
  software/feedcord.yml
  software/feedmixer.yml
  software/fenrus.yml
  software/fess.yml
  software/fhem.yml
  software/files-sharing.yml
  software/filestash.yml
  software/firefox-account-server.yml
  software/firezone.yml
  software/flashpaper.yml
  software/flatnotes.yml
  software/flexisip.yml
  software/flowforge.yml
  software/foodcoopshop.yml
  software/foodsoft.yml
  software/fossbilling.yml
  software/freescout.yml
  software/freshrss.yml
  software/fusion.yml
  software/fusionpbx.yml
Labels: enhancement, curation, reviewers wanted

#1323 General clean up of projects beginning with G
  software/galene.yml
  software/galette.yml
  software/gamevault.yml
  software/gancio.yml
  software/ganymede.yml
  software/garagehq.yml
  software/gaseous-server.yml
  software/gathio.yml
  software/gatus.yml
  software/genea.app.yml
  software/geneweb.yml
  software/gerbera.yml
  software/gerrit.yml
  software/gibbon.yml
  software/gitbucket.yml
  software/gitolite.yml
  software/gladys.yml
  software/glance.yml
  software/glitchtip.yml
  software/gnunet.yml
  software/go-doxy.yml
  software/gophish.yml
  software/goploader.yml
  software/gossa.yml
  software/gosɛ.yml
  software/gotenberg.yml
  software/gotify.yml
  software/gotosocial.yml
  software/grist.yml
  software/grocy.yml
  software/group-office.yml
  software/guacamole.yml
Labels: enhancement, curation

#1324 General clean up of projects beginning with H and I
  software/habitica.yml
  software/handbrake-web.yml
  software/haraka.yml
  software/healthchecks.yml
  software/heimdall.yml
  software/hiccup.yml
  software/hitobito.yml
  software/holoplay.yml
  software/homarr.yml
  software/home-assistant.yml
  software/homebox-sysadminsmedia.yml
  software/homegallery.yml
  software/homelabos.yml
  software/homepage-by-gethomepage.yml
  software/homer.yml
  software/homeserverhq.yml
  software/hook0.yml
  software/hoppscotch-community-edition.yml
  software/hortusfox.yml
  software/htmly.yml
  software/hubleys.yml
  software/huginn.yml
  software/huly.yml
  software/hyperkitty.yml
  software/hyperswitch.yml
  software/i-librarian.yml
  software/ilias.yml
  software/imgproxy.yml
  software/immich-kiosk.yml
  software/immich.yml
  software/inboxen.yml
  software/indico.yml
  software/input.yml
  software/inveniordm.yml
  software/inventree.yml
  software/invoiceplane.yml
  software/invoiceshelf.yml
  software/isponsorblocktv.yml
  software/itflow.yml
Labels: enhancement, curation, reviewers wanted

#1273 Add Superdesk
  software/superdesk.yml
Labels: addition

#1280 Add ChartDB
  software/chartdb.yml
Labels: addition

#1303 Add VoucherVault
  software/vouchervault.yml
Labels: addition

#1278 Add Dawarich
  software/dawarich.yml
Labels: addition

#1289 Add Frappe Helpdesk
  software/frappe-helpdesk.yml
Labels: addition

#1306 feat: added "One Time Secret"
  software/one-time-secret.yml
Labels: addition

#1314 add evcc
  software/evcc.yml
Labels: addition

#1320 add Spoolman
  software/spoolman.yml
Labels: addition

#1341 Update OpenBudgeteer license
  software/openbudgeteer.yml
Labels: bug
