Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2025-01, with the labels that each got.

#1048 Remove Iconcapatcha (Unmaintained since December 2023)
  software/iconcaptcha.yml
Labels: curation

#1049 Remove Anuko (Unmaintained since December 2023)
  software/anuko.yml
Labels: curation

#1050 Remove betanin (Unmaintained since December 2023)
  software/betanin.yml
Labels: curation

#1051 Remove Bsimp (Unmaintained since December 2023)
  software/bsimp.yml
Labels: curation

#1030 add repoflow
  software/repoflow.yml
Labels: addition, non-free

#1041 Add LHA to Internet of Things (IoT)
  software/lha.yml
Labels: addition

#1052 Remove Dim (Unmaintained since December 2023)
  software/dim.yml
Labels: curation

#1077 Remove Noisedash (Unmaintained since Jan 2024)
  software/noisedash.yml
Labels: curation

#1079 Remove ASTPP (Unmaintained since Jan 2024)
  software/astpp.yml
Labels: curation

#1082 Remove Simply Shorten (Unmaintained since Nov 2023)
  software/simply-shorten.yml
Labels: curation

#1078 Remove Octave Online (Unmaintained since Jan 2024)
  software/octave-online.yml
Labels: curation

#1080 Remove Mailygo (Unmaintained since 2020, Archived)
  software/mailygo.yml
Labels: curation

#1083 Remove Kbin and associated link (Unmaintained since Dec 2023)
  markdown/footer.md
  software/kbin.yml
Labels: curation

#1094 Add / Remove URL links, Fix License
  .hecat/url-check.yml
  software/medusa.yml
  software/microweber.yml
  software/oxid-eshop.yml
Labels: tools, curation, reviewers wanted

#1093 Remove Local Food Nodes (Deleted Repo)
  software/local-food-nodes.yml
Labels: curation, reviewers wanted

#1092 tools/hecat: update copyright year to 2025
  .hecat/conf.py
Labels: tools

#1091 Remove Goeland (Unmaintained since Jan 2024)
  software/goeland.yml
Labels: curation

#1056 Add DigiQuiz to Miscellaneous
  software/digiquiz.yml
Labels: addition

#1055 Add DigiFlashcards to Miscellaneous
  software/digiflashcards.yml
Labels: addition

#1053 Add digisteps to Misc
  software/digisteps.yml
Labels: addition

#1070 Add Digirecord to File Transfer - Single Click & dragndrop upload
  software/digirecord.yml
Labels: addition

#1068 Add Digicut to Miscellaneous
  software/digicut.yml
Labels: addition

#1060 add MyFin
  software/myfin.yml
Labels: addition

#911 add Mybucks.online
  software/mybucks.online.yml
Labels: addition

#1025 Added Composio
  software/composio.yml
Labels: addition

#1067 Add Digiread to Misc
  software/digiread.yml
Labels: addition

#1076 Add Localess
  software/localess.yml
Labels: addition

#1071 Add postiz
  software/postiz.yml
Labels: addition

#1098 Remove DaneeCloud (the project is archived)
  software/daneecloud.yml
Labels: curation

#1097 Update romm.yml
  software/romm.yml
Labels: enhancement

#1100 Remove OTS-Share (Unmaintained since Jan 2024)
  software/ots-share.yml
Labels: curation, reviewers wanted

#1102 Update pdfding.yml - Add demo url and update description
  software/pdfding.yml
Labels: enhancement, reviewers wanted

#1108 Fix yopass tags
  software/yopass.yml
Labels: enhancement

#1110 Remove Darkwire.io (Unmaintained since Jan 2024)
  software/darkwire.io.yml
Labels: curation, reviewers wanted

#1107 Fix Papermerge (New GH Link)
  software/papermerge.yml
Labels: enhancement, reviewers wanted

#1028 Add clipbucket.yml
  software/clipbucket.yml
Labels: addition

#978 Add HomeServerHQ
  software/homeserverhq.yaml
Labels: addition

#1090 feat: added Gotenberg, a Docker-powered stateless API for PDF files
  software/gotenberg.yml
Labels: addition

#1105 PULL_REQUEST_TEMPLATE.md: clarify demo credentials requirements
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#1113 fix: correct license and platforms for Manticore Search
  software/manticore-search.yml
Labels: enhancement

#1117 remove adminerevo (project archived)
  software/adminerevo.yml
Labels: curation

#1112 Remove YoutubeDL-Material (Unmiantained since Jan 2024)
  .hecat/url-check.yml
  software/youtubedl-material.yml
Labels: curation

#1085 Add Tegon
  software/tegon.yml
Labels: addition

#1026 add 4ga Boards
  software/4ga-boards.yml
Labels: addition

#1034 Add channeltube.yml
  software/channeltube.yml
Labels: addition

#1061 Adding "Feeds Fun" feed reader
  software/feeds-fun.yml
Labels: addition

#1115 Remove Exbin (Unmaintained since Jan 2024)
  software/exbin.yml
Labels: curation

#1120 Remove Bolt-CMS (Unmaintained since Jan 2024)
  software/bolt-cms.yml
Labels: curation, reviewers wanted

#1125 Remove Psychic (source code gone)
  software/psychic.yml
Labels: bug, curation

#1089 Add Depends Flag to Youtube and Spotify Apps
  software/lidatube.yml
  software/mopidy.yml
  software/stretto.yml
  software/tube.yml
Labels: enhancement, discussion, reviewers wanted
