Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2025-05, with the labels that each got.

#1330 General clean up of projects beginning with M
  software/maddy-mail-server.yml
  software/magento-open-source.yml
  software/mailcatcher.yml
  software/mailcow.yml
  software/mailman.yml
  software/mailu.yml
  software/mainsail.yml
  software/maloja.yml
  software/manage-my-damn-life.yml
  software/manifest.yml
  software/mantisbt.yml
  software/maptiler-server.yml
  software/mataroa.yml
  software/matchering.yml
  software/mathesar.yml
  software/matomo.yml
  software/mautic.yml
  software/mayan-edms.yml
  software/mediacms.yml
  software/mediagoblin.yml
  software/mediawiki.yml
  software/medusajs.yml
  software/meetable.yml
  software/mejiro.yml
  software/memex.yml
  software/memos.yml
  software/mere-medical.yml
  software/meshcentral.yml
  software/metabase.yml
  software/microweber.yml
  software/mindsdb.yml
  software/miniflux.yml
  software/minimal-git-server.yml
  software/minio.yml
  software/mirotalk-c2c.yml
  software/misago.yml
  software/mistborn.yml
  software/mixpost.yml
  software/mobilizon.yml
  software/modoboa.yml
  software/modx.yml
  software/moodle.yml
  software/motion.tools-antragsgrün.yml
  software/mstream.yml
  software/mta-sa.yml
  software/mybucks.online.yml
  software/myfin-budget.yml
Labels: enhancement, curation, reviewers wanted

#1325 General clean up of projects beginning with J, K and L
  software/iopaint.yml
  software/jami.yml
  software/jelu.yml
  software/jitbit-helpdesk.yml
  software/jitsi-meet.yml
  software/joplin.yml
  software/judge0-ce.yml
  software/jump.yml
  software/kanboard.yml
  software/keila.yml
  software/keygen.yml
  software/keystonejs.yml
  software/kill-bill.yml
  software/kimai.yml
  software/kinto.yml
  software/kitchenowl.yml
  software/known.yml
  software/kong.yml
  software/kresus.yml
  software/kutt.yml
  software/lago.yml
  software/lama-cleaner.yml
  software/lazylibrarian.yml
  software/leantime.yml
  software/lemmy.yml
  software/leon.yml
  software/lha.yml
  software/libre-translate.yml
  software/libreddit.yml
  software/librekb.yml
  software/librephotos.yml
  software/libretime.yml
  software/librum.yml
  software/lidarr.yml
  software/lila.yml
  software/limbas.yml
  software/limesurvey.yml
  software/linkace.yml
  software/linkding.yml
  software/linkwarden.yml
  software/liteshort.yml
  software/littlelink.yml
  software/livecodes.yml
  software/livestreamdvr.yml
  software/liwan.yml
  software/lodestone.yml
  software/loomio.yml
  software/luanti.yml
  software/lubelogger.yml
  software/lura.yml
  software/lychee.yml
Labels: enhancement, curation

#1335 General clean up of projects beginning with N and O
  licenses.yml
  software/nefarious.yml
  software/neko.yml
  software/neonlink.yml
  software/newsblur.yml
  software/newspipe.yml
  software/nginx-proxy-manager.yml
  software/ngircd.yml
  software/nocodb.yml
  software/nodebb.yml
  software/noosfero.yml
  software/note-mark.yml
  software/novu.yml
  software/nullboard.yml
  software/october.yml
  software/octobot.yml
  software/octoprint.yml
  software/ocular.yml
  software/oddmuse.yml
  software/olivetin.yml
  software/ombi.yml
  software/omeka-s.yml
  software/onionshare.yml
  software/open-meteo.yml
  software/openbudgeteer.yml
  software/opencart.yml
  software/opengist.yml
  software/openmediavault.yml
  software/openmeetings.yml
  software/openolat.yml
  software/openproject.yml
  software/openremote.yml
  software/openrouteservice.yml
  software/opensearch.yml
  software/opensign.yml
  software/opensips.yml
  software/openslides.yml
  software/openttd.yml
  software/openziti.yml
  software/orangehrm.yml
  software/ossn.yml
  software/otobo.yml
  software/otter-wiki.yml
  software/our-shopping-list.yml
  software/outline.yml
  software/ovenmediaengine.yml
  software/overseerr.yml
  software/paaster.yml
Labels: enhancement, curation, reviewers wanted

#1350 Move Kiwix Tag
  software/kiwix-serve.yml
Labels: bug

#1315 add Kapowarr
  software/kapowarr.yml
Labels: addition

#1321 add OpenEMR
  software/openemr.yml
Labels: addition

#1331 Add Daily Stars Explorer
  software/daily-stars-explorer.yml
Labels: addition

#1361 fix website of Fork Recipes
  software/fork-recipes.yml
Labels: bug

#1319 add SafeLine
  software/safeline.yml
Labels: addition

#1363 Create Health and Fitness Tag
  software/endurain.yml
  software/fasten-health.yml
  software/mere-medical.yml
  software/openemr.yml
  software/wger.yml
  tags/health-and-fitness.yml
Labels: enhancement, reviewers wanted

#1339 Add Webtor
  software/webtor.yml
Labels: addition

#1346 Add Mergeable
  software/mergeable.yml
Labels: addition

#1360 Remove trilium-notes (unmaintained)
  software/trilium-notes.yml
Labels: curation

#1359 triliumnext-notes: add
  software/triliumnext-notes.yml
Labels: addition

#1379 update inventaire source code URL
  software/inventaire.yml
Labels: bug

#1377 Remove Jump (Unmaintained since May 2024)
  software/jump.yml
Labels: curation

#1333 doc: update CONTRIBUTING.md (clarify removal criteria/what does not qualify)
  CONTRIBUTING.md
Labels: documentation

#1357 Add ByteStash
  software/bytestash.yml
Labels: addition

#1351 Add Statistics for Strava
  software/statistics-for-strava.yml
Labels: addition

#1385 Update Liwan License
  software/liwan.yml
Labels: bug

#1384 Remove Releasebell (Invalid for awesome-selfhosted)
  software/releasebell.yml
Labels: curation

#1344 General clean up of projects beginning with P and Q
  software/pacebin.yml
  software/pagure.yml
  software/pairdrop.yml
  software/panora.yml
  software/part-db.yml
  software/passbolt.yml
  software/passky.yml
  software/password-pusher.yml
  software/pastefy.yml
  software/pdfding.yml
  software/peergos.yml
  software/penpot.yml
  software/phorge.yml
  software/photoview.yml
  software/phpoffice.yml
  software/pi-hole.yml
  software/picoshare.yml
  software/picsur.yml
  software/pictshare.yml
  software/pigallery-2.yml
  software/pimcore.yml
  software/pinepods.yml
  software/pingvin-share.yml
  software/pixelfed.yml
  software/plainpad.yml
  software/plane.yml
  software/plausible-analytics.yml
  software/plik.yml
  software/plugnmeet.yml
  software/pocketbase.yml
  software/pomerium.yml
  software/pomjs.yml
  software/portkey.yml
  software/postal.yml
  software/postiz.yml
  software/prestashop.yml
  software/pretix.yml
  software/prisme-analytics.yml
  software/privatebin.yml
  software/projeqtor.yml
  software/psitransfer.yml
  software/psono.yml
  software/pufferpanel.yml
  software/pushbits.yml
  software/pyload.yml
  software/qloapps.yml
  software/quickshare.yml
  software/quizmaster.yml
Labels: enhancement, curation

#1388 Update directus license
  software/directus.yml
Labels: bug, non-free

#1383 Remove Ltsu (Unmaintained since May 2024)
  software/lstu.yml
Labels: curation

#1390 Remove turndown (Unmaintained since May 2024)
  software/turndown.yml
Labels: curation

#1389 Remove Gitblit (Unmaintained since May 2024)
  software/gitblit.yml
Labels: curation

#1391 Remove DocKing (Unmaintained since May 2024)
  software/docking.yml
Labels: curation

#1342 Add WeddingShare to Photo and Video Galleries
  software/weddingshare.yml
Labels: addition

#1394 Update WeddingShare Urls to correct domain
  software/weddingshare.yml
Labels: bug

#1362 add Vince
  software/vince.yml
Labels: addition

#1399 Fix Omeka S Description
  software/omeka-s.yml
Labels: bug

#1398 Remove Eqivo (Unmaintained since May 2024)
  software/eqivo.yml
Labels: curation, reviewers wanted

#1400 Remove Trudesk (Unmaintained since July 2024, Broken functionality)
  software/trudesk.yml
Labels: curation

#1401 Remove Mailcatcher (Umaintained since May 2024)
  software/mailcatcher.yml
Labels: curation

#1410 Remove Gitolite (Unmaintained since May 2024), Fix InvoiceNinja License
  software/gitolite.yml
  software/invoice-ninja.yml
Labels: bug, curation, non-free
