Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2025-09, with the labels that each got.

#1562 Add Colanode
  software/colanode.yml
Labels: addition

#1576 Add Medama Analytics
  software/medama-analytics.yml
Labels: addition

#1588 Add Listaway to Task Management
  software/listaway.yml
Labels: addition

#1599 add tinyfeed
  software/tinyfeed.yml
Labels: addition

#1627 [clink, pacebin] update to new Forgejo URLs
  software/clink.yml
  software/pacebin.yml
Labels: bug, curation

#1601 Add Vanilla Cookbook
  software/vanilla-cookbook.yml
Labels: addition

#1589 Add Nirvati
  software/nirvati.yml
Labels: addition

#1656 remove software/minimalist-web-notepad (unmaintained since Sep 2024)
  software/minimalist-web-notepad.yml
Labels: curation

#1676 fix the-epube website URL
  software/the-epube.yml
Labels: bug

#1641 Add Warracker – A self-hosted warranty tracker
  software/warracker.yml
Labels: addition

#1688 Update kuvasz-uptime.yml
  software/kuvasz-uptime.yml
Labels: enhancement, reviewers wanted
