Repository awesome-selfhosted/awesome-selfhosted-data, pull requests merged in 2025-07, with the labels that each got.

#1465 Exclude OpenSpeedTest from last updated check
  .hecat/awesome-lint-strict.yml
  .hecat/awesome-lint.yml
Labels: curation, reviewers wanted

#1417 add spooty
  software/spooty.yml
Labels: addition

#1473 remove rustdesk
  software/rustdesk.yml
Labels: curation

#1471 Update Directory Lister
  software/directory-lister.yml
Labels: bug

#1475 Remove Librum (Unmaintained since July 2024)
  software/librum.yml
Labels: curation

#1476 Remove Dnote (Unmaintained since July 2024)
  software/dnote.yml
Labels: curation

#1459 Addition of Papra
  software/papra.yml
Labels: addition

#1472 Add Signature PDF
  software/signature-pdf.yml
Labels: addition

#1457 Add LibreBooking
  software/librebooking.yml
Labels: addition

#1429 Add 42links with its license
  .hecat/export-html.yml
  .hecat/export-markdown.yml
  licenses-nonfree.yml
  software/42links.yml
Labels: addition, non-free

#1461 Add Halo to Software Development Low Code
  software/halo.yml
Labels: addition

#1500 Change Dagu to Automation category
  software/dagu.yml
Labels: enhancement

#1495 Updated chhoto-url.yml
  software/chhoto-url.yml
Labels: enhancement

#1493 Change tags from Note-taking & Editors to Wikis in oddmuse.yml
  software/oddmuse.yml
Labels: enhancement, reviewers wanted

#1501 Remove etebase sync (Unmaintained since Jul 2024)
  software/etebase-etesync.yml
Labels: curation

#1487 Remove Paperless-AI
  software/paperless-ai.yml
Labels: curation

#1376 Create Telebugs
  software/telebugs.yml
Labels: addition, non-free

#1510 Add photoview demo url
  software/photoview.yml
Labels: enhancement

#1558 Remove Holoplay (unmaintained since Jul 2024)
  software/holoplay.yml
Labels: curation, reviewers wanted
